name: Trigger Kubeflow Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v2
#       - name: Trigger Kubeflow Pipeline
#         uses: actions/checkout@v2
#         with:
#           PIPELINE_NAME: hf-t5-model-load-clr
#           pipeline_parameters: ''
#         env:
#           KFP_ENDPOINT: https://kubeflow.kubeflow.dev.cloudtrust.rocks
#           KFP_USERNAME: sbaig1@informatica.com
#           KFP_PASSWORD: iSHEZAN@123
      - name: Kubeflow compile, deploy and run.
        # You may pin to the exact commit or the version.
        # uses: NikeNano/kubeflow-github-action@3f07122a54dfcde71ac28246e4059dd38a18d589
        uses: actions/checkout@v2
        with:
          # The endpoint where your Kubeflow UI is running.
          KUBEFLOW_URL: https://kubeflow.kubeflow.dev.cloudtrust.rocks
          # The IAP client id, which was specified when the kubeflow deployment where setup using IAP.
          #CLIENT_ID: # optional
          # The full path name including the filename of the python file that describes the pipeline you want to run on Kubeflow.  This should be relative to the root of the GitHub repository where the Action is triggered.
          #PIPELINE_CODE_PATH: # optional
          # The name of the pipeline, this name will be the name of the pipeline in the Kubeflow UI.
          #PIPELINE_FUNCTION_NAME: # optional
          # The base64 encoded google credentials
          #ENCODED_GOOGLE_APPLICATION_CREDENTIALS: 
          # The path to the decoded google credentials
          #GOOGLE_APPLICATION_CREDENTIALS: 
          # The name of the experiment name within which the kubeflow experiment should run
          #EXPERIMENT_NAME: # optional
          # The namespace in which the pipeline should run
          #PIPELINE_NAMESPACE: # optional
          # Should github action also trigger the pipeline
          RUN_PIPELINE: hf-t5-model-load-clr
          # Should github action also trigger the pipeline
          #VERSION_GITHUB_SHA: # optional
        env:
          KFP_ENDPOINT: https://kubeflow.kubeflow.dev.cloudtrust.rocks
          KFP_USERNAME: sbaig1@informatica.com
          KFP_PASSWORD: iSHEZAN@123
