name: Trigger Kubeflow Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Kubeflow Pipeline
        uses: actions/checkout@v2
        with:
          pipeline_name: hf-t5-model-load-clr
          pipeline_parameters: ''
        env:
          KFP_ENDPOINT: https://kubeflow.kubeflow.dev.cloudtrust.rocks
          KFP_USERNAME: sbaig1@informatica.com
          KFP_PASSWORD: iSHEZAN@123
